

import { ReactNode } from 'react';
import { Metadata } from 'next';
import { Mulish } from 'next/font/google';
import './globals.css';
import Firstrefresh from '@/components/FirstRefresh';
import NextTopLoader from 'nextjs-toploader';
import ScrollToTop from '@/components/ui/ScrollEffect';
const mulish = Mulish({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Fashion Cart: A Complete Ecommerce Website',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
  noHeaderfooter?: string;
}



/**
 * Root layout component for the application.
 * @component
 * @param {Object} props - Props for the RootLayout component.
 * @param {React.ReactNode} props.children - The children components to be rendered within the layout.
 * @param {string} [props.noHeaderfooter] - Optional string indicating no header or footer should be displayed.
 * @returns {JSX.Element} JSX element representing the RootLayout component.
 */

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        {/* NextTopLoader */}
        <NextTopLoader
          color="#f57e5d"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3.5}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={4000}
        />
        {/* first time open site then show pop up  */}
        <Firstrefresh />
        <ScrollToTop />
        <main>{children}</main>
      </body>
    </html>
  );
}
